# Generated by Django 5.0.1 on 2024-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_otp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Client", "Client"),
                    ("Saloon Staff", "Saloon Staff"),
                    ("Admin", "Admin"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
