# Generated by Django 5.0.1 on 2024-02-15 17:04

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("shop_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "shop_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[("Private", "Private"), ("Public", "Public")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "business_days",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_hours_open",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_hours_close",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "special_features",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.upload_shop_logo_path,
                    ),
                ),
                ("verify_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "street_address1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_address2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=30, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=30, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopExterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.upload_shop_exterior_path,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_exterior",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopInterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.upload_shop_interior_path,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_interior",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[("Hair Cut", "Hair Cut")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("price", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_services",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(blank=True, max_length=200, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.upload_staff_photo_path,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_staffs",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.upload_shop_work_path,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_work",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
    ]
