# Generated by Django 5.0.2 on 2024-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopstaff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='payment_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='service_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='staff_setup',
            field=models.BooleanField(default=False),
        ),
    ]
