# Generated by Django 5.0.2 on 2024-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_payment_setup_shop_registration_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
