# Generated by Django 5.0.2 on 2024-03-13 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
