# Generated by Django 5.0.2 on 2024-03-04 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=200, null=True)),
                ('service_type', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('re_scheduled', models.BooleanField(default=False)),
                ('booking_rescheduled_at', models.DateTimeField(blank=True, null=True)),
                ('split', models.BooleanField(default=False)),
                ('booking_split_at', models.DateTimeField(blank=True, null=True)),
                ('amount_to_pay', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_price', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Rescheduled', 'Rescheduled'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('Review', 'Review'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=255, null=True)),
                ('booking_start', models.DateTimeField(blank=True, null=True)),
                ('booking_end', models.DateTimeField(blank=True, null=True)),
                ('booking_approved_at', models.DateTimeField(blank=True, null=True)),
                ('booking_declined_at', models.DateTimeField(blank=True, null=True)),
                ('booking_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_service_bookings', to='shop.shopservice')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='bookings.booking')),
            ],
        ),
    ]
