# Generated by Django 5.0.2 on 2024-03-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_shop'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_chat_rooms', to='chats.privatechatroom'),
            preserve_default=False,
        ),
    ]
