# Generated by Django 5.0.2 on 2024-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='home_service',
            field=models.BooleanField(default=False),
        ),
    ]
