# Generated by Django 5.0.2 on 2024-03-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_booking_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_staff',
            new_name='booked_staff',
        ),
    ]
