# Generated by Django 5.0.2 on 2024-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookingrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_split_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_split_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_split_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
