# Generated by Django 5.0.2 on 2024-03-13 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_walkinbooking'),
        ('shop', '0002_shopstaff_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkinbooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='walkinbooking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='walkinbooking',
            name='service',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_staffs', to='shop.shopstaff'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_service_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_service_bookings', to='shop.shopservice'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_bookings', to='shop.shop'),
        ),
    ]
