# Generated by Django 5.0.2 on 2024-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_walkinbooking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='home_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='split',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
